### ISSUE TITLE
Support for other card types

### ISSUE THREAD

**Issue by geekdave** [ben/hubot-tangocard-highfive#1]
Hey!  I saw your talk at CascadiaFest, and was inspired to check this out for my team!

I saw in the README that other card types is on the TODO list.  Would be happy to look into a PR for this.  

I just signed up for TangoCard but don't yet have visibility into their API.  

For this line: 
https://github.com/ben/hubot-tangocard-highfive/blob/0b136e37b199d00c0612209bd65255d797a2b491/src/lib/api/tangocard.coffee#L33

1) Where did you get the SKU from?  Is there a list of available SKUs?
2) Do you know if Tango supports buying a TangoCard via their API (my understanding is this allows the recipient to select which specific card, or non-profit they want to use)

Thanks!

**Comment by ben** [comment]
Awesome, welcome!

When the account rep gets back to you, they'll likely point you toward their [API documentation](https://github.com/tangocarddev/RaaS#reward-resources), which has a pointer to an [interactive API sandbox](https://integration-www.tangocard.com/raas_api_console/). You won't be able to use most of it without some credentials, but check out the "List of rewards" API, that's where the SKUs come from. And yes, the first one in the list is the "Tango" card.

**Comment by geekdave** [comment]
Awesome!  Just what I need.  Looking forward to this little social/corporate experiment :)
