### ISSUE TITLE
Periodic issues with Tango

### ISSUE THREAD

**Issue by nickpleis** [ben/hubot-tangocard-highfive#13]
Periodically (with increasing frequency) we're seeing an error that looks like:

```
SyntaxError: Unexpected token <
at Object.parse (native)
at /opt/bot/node_modules/hubot-tangocard-highfive/src/lib/tango.coffee:41:27
at IncomingMessage.<anonymous> (/opt/bot/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
at IncomingMessage.emit (events.js:129:20)
at _stream_readable.js:908:16
at process._tickCallback (node.js:355:11)
```

At this point I'm not entirely clear about what I'm seeing or really how to make this more fault tolerant....

**Comment by ben** [comment]
Was the client-IP issue the root of this? I haven't had much time to work with Highfive in a while, but I'd love to add you as a maintainer if you're interested.

**Comment by t-richards** [comment]
>Was the client-IP issue the root of this?

Yes, it looks like the jsonip.com service is either erroring out or blocking requests frequently.
