### ISSUE TITLE
highfive config URL not working

### ISSUE THREAD

**Issue by geekdave** [ben/hubot-tangocard-highfive#2]
Howdy!  I've got my TangoCard sandbox account all ready to go.  Just working on getting the bot set up.

I've got the bot responding to `highfive config` with a URL, but when I go to the URL, I get "Connection Refused". 

The server is definitely the right hostname - for some reason there just isn't anything listening.  Not sure if there was some prerequisite for setting up a server?  This is on an internal CentOS VM.  I'm pretty sure it's not a firewall issue, since I'm unable to `telnet localhost 443` while logged into the hubot server either.

Any thoughts would be much appreciated!

**Comment by geekdave** [comment]
Was able to do all my configuration using environment variables, so this isn't blocking me anymore.  But still getting the same issue.

**Comment by ben** [comment]
Can you get to `/`? Have you tried plain http? What about running Hubot locally (`bin/hubot`)? This plugin relies on Hubot's built-in web server, which I believe is based on Express, so my first suspicion is that it's a network issue with your hosting setup.

**Comment by geekdave** [comment]
Aha!  The docs provide all answers:

https://github.com/github/hubot/blob/master/docs/scripting.md#http-listener

> It listens on the port specified by the EXPRESS_PORT or PORT environment variables (preferred in that order) and defaults to 8080. 

I was assuming port 80.  But switching to 8080 worked like a charm!
